# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConstraintTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConstraintTest
	pod 'Alamofire', '~> 4.7'
  	pod 'AlamofireImage'
    	pod 'SwiftyJSON', '~> 4.0'


end
